/**
 * Species reference data for the demo.
 * Real Bornean / Sarawak flora, matching the Niah National Park framing in
 * the client's project scope. Conservation codes follow the IUCN list in the
 * schema; treat them as demo content, not an authoritative assessment.
 */
export const SPECIES = [
  {
    scientific_name: 'Rafflesia tuan-mudae', common_name: 'Rafflesia', local_name: 'Bunga Pakma',
    family: 'Rafflesiaceae', genus: 'Rafflesia', species_epithet: 'tuan-mudae',
    growth_form: 'parasite', conservation: 'EN',
    description: 'A holoparasite with no stem, leaves or roots of its own, living entirely inside the tissue of Tetrastigma vines and emerging only to flower. Among the largest single flowers in the world, reaching about one metre across.',
    characteristics: 'No chlorophyll. Visible only as a cabbage-like bud for up to nine months before opening; the open flower lasts four to six days and smells of carrion, which attracts the flies that pollinate it.',
    leaf_description: 'None. The vegetative body is a thread-like network of filaments inside the host vine.',
    flower_description: 'Five thick brick-red lobes covered in pale warts, surrounding a deep central chamber with a raised disk bearing spiny processes. Unisexual.',
    fruit_description: 'A woody berry to 15 cm across holding thousands of minute seeds in a sticky pulp, probably dispersed by tree shrews and ground squirrels.',
    habitat: 'Primary and old secondary lowland and hill dipterocarp forest, on shaded slopes where its Tetrastigma host is established.',
    distribution: 'Endemic to Borneo; recorded in Sarawak at Gunung Gading, Sri Aman and scattered hill forest sites.',
  },
  {
    scientific_name: 'Nepenthes ampullaria', common_name: 'Flask-shaped pitcher plant', local_name: 'Periuk Kera',
    family: 'Nepenthaceae', genus: 'Nepenthes', species_epithet: 'ampullaria',
    growth_form: 'climber', conservation: 'LC',
    description: 'A pitcher plant that has largely given up trapping insects. It forms dense carpets of squat ground pitchers that collect and digest falling leaf litter, making it partly detritivorous.',
    characteristics: 'Rosettes of ground pitchers spread across the forest floor from creeping stems; upper pitchers are sparse or absent. Pitcher fluid hosts a whole community of mosquito larvae, midges and frogs.',
    leaf_description: 'Lanceolate, 8-25 cm long, tapering into a tendril that swells into the pitcher.',
    flower_description: 'Small reddish-brown flowers in a branched panicle to 40 cm; plants are dioecious.',
    fruit_description: 'A dry capsule splitting into four valves, releasing thread-like wind-borne seeds.',
    habitat: 'Peat swamp forest, kerangas (heath forest) and damp shaded sites on sandy soil.',
    distribution: 'Borneo, Sumatra, Peninsular Malaysia, Singapore, Thailand and New Guinea. Common across lowland Sarawak.',
  },
  {
    scientific_name: 'Nepenthes rafflesiana', common_name: 'Raffles pitcher plant', local_name: 'Periuk Kera Raja',
    family: 'Nepenthaceae', genus: 'Nepenthes', species_epithet: 'rafflesiana',
    growth_form: 'climber', conservation: 'LC',
    description: 'A highly variable climbing pitcher plant with strikingly dimorphic traps: bulbous speckled lower pitchers and slender funnel-shaped upper pitchers carried high in the canopy.',
    characteristics: 'Lower pitchers sit on the ground with two fringed wings; upper pitchers hang from tendrils and are wingless. Colour ranges from pale green to deep maroon speckling.',
    leaf_description: 'Leathery, oblong-lanceolate to 40 cm, with a prominent midrib extending into the tendril.',
    flower_description: 'Racemes to 70 cm of small reddish flowers, strongly scented at night in some forms.',
    fruit_description: 'Capsule 15-30 mm, four-valved, with numerous thread-like seeds.',
    habitat: 'Kerangas, peat swamp margins, coastal scrub and disturbed open ground on poor sandy soils.',
    distribution: 'Borneo, Sumatra, Peninsular Malaysia and Singapore. Widespread in the Sarawak lowlands.',
  },
  {
    scientific_name: 'Eusideroxylon zwageri', common_name: 'Bornean ironwood', local_name: 'Belian',
    family: 'Lauraceae', genus: 'Eusideroxylon', species_epithet: 'zwageri',
    growth_form: 'tree', conservation: 'VU',
    description: 'One of the densest and most durable timbers in the world. Belian sinks in water, resists termites and marine borers, and standing trees can exceed a thousand years of age.',
    characteristics: 'Extremely slow growing. Heartwood darkens from yellow to near black on exposure. Heavily logged for shingles, bridges and house posts, and now protected in Sarawak.',
    leaf_description: 'Alternate, elliptic to oblong, 10-20 cm, leathery, glossy dark green above with a pale underside; the young flush is bright red.',
    flower_description: 'Small yellowish-green flowers in short axillary panicles, faintly scented.',
    fruit_description: 'A very large ovoid drupe 10-18 cm long with a thick woody shell, the largest fruit in the laurel family. Dispersed by gravity and by bearded pigs.',
    habitat: 'Lowland mixed dipterocarp forest on well-drained clay and sandy soils, often along ridges and riverbanks below 500 m.',
    distribution: 'Borneo, Sumatra, Palawan and the southern Philippines. Widespread but heavily depleted in Sarawak.',
  },
  {
    scientific_name: 'Shorea macrophylla', common_name: 'Engkabang tree', local_name: 'Engkabang Jantong',
    family: 'Dipterocarpaceae', genus: 'Shorea', species_epithet: 'macrophylla',
    growth_form: 'tree', conservation: 'EN',
    description: 'The principal source of illipe nut, an oil-rich seed harvested by Iban and other communities and exported as a cocoa butter substitute. Masts irregularly, at intervals of three to seven years.',
    characteristics: 'Fast growing for a dipterocarp and widely planted along rivers. Bole to 40 m with pale grey, shallowly fissured bark and clear resin.',
    leaf_description: 'Large, oblong to elliptic, 15-35 cm, with 14-20 pairs of parallel secondary veins; stipules conspicuous on young shoots.',
    flower_description: 'Cream to pale yellow, fragrant, borne in axillary panicles during mast years.',
    fruit_description: 'A nut about 4 cm enclosed by three long and two short wings, spinning as it falls. Seeds are recalcitrant and must be sown within days.',
    habitat: 'Alluvial flats and riverbanks in lowland mixed dipterocarp forest, tolerant of seasonal flooding.',
    distribution: 'Endemic to Borneo, chiefly Sarawak and West Kalimantan; widely planted in agroforestry.',
  },
  {
    scientific_name: 'Dryobalanops aromatica', common_name: 'Borneo camphorwood', local_name: 'Kapur',
    family: 'Dipterocarpaceae', genus: 'Dryobalanops', species_epithet: 'aromatica',
    growth_form: 'tree', conservation: 'CR',
    description: 'An emergent giant to 65 m, historically the source of Borneo camphor, once traded to China at a higher price than gold. Famous for crown shyness, where neighbouring canopies never quite touch.',
    characteristics: 'Crystalline camphor forms in cavities in the trunk of old trees. Timber is sold as kapur. Populations have collapsed through logging across the range.',
    leaf_description: 'Ovate to lanceolate, 6-12 cm, glossy, with a finely pointed tip, aromatic when crushed.',
    flower_description: 'White, fragrant, about 2 cm across, in short axillary racemes.',
    fruit_description: 'A nut seated in a cup, with five long strap-shaped wings to 10 cm that autorotate in the wind.',
    habitat: 'Well-drained sandy or loamy soils in lowland dipterocarp forest, often gregarious and forming near pure stands.',
    distribution: 'Borneo, Sumatra and Peninsular Malaysia. In Sarawak now restricted to protected and remnant forest.',
  },
  {
    scientific_name: 'Koompassia excelsa', common_name: 'Tualang', local_name: 'Tapang',
    family: 'Fabaceae', genus: 'Koompassia', species_epithet: 'excelsa',
    growth_form: 'tree', conservation: 'LC',
    description: 'Among the tallest tropical trees, reaching 85 m with a smooth pale trunk and enormous buttresses. Culturally protected because giant honey bees nest in its limbs.',
    characteristics: 'The slippery bark deters bears and other climbers, which is why Apis dorsata colonies favour it. Felling a tapang is taboo in many Iban communities and the tree is legally protected in Sarawak.',
    leaf_description: 'Pinnate with 5-9 alternate leaflets, each 3-8 cm, leathery and blunt-tipped.',
    flower_description: 'Small greenish-white flowers massed in axillary panicles, attracting large numbers of bees.',
    fruit_description: 'A flat, thin, winged pod 8-15 cm containing a single seed, dispersed by wind from great height.',
    habitat: 'Lowland mixed dipterocarp forest on well-drained soils, typically as a scattered emergent.',
    distribution: 'Borneo, Sumatra, Peninsular Malaysia, Thailand and the Philippines.',
  },
  {
    scientific_name: 'Gonystylus bancanus', common_name: 'Ramin', local_name: 'Ramin Melawis',
    family: 'Thymelaeaceae', genus: 'Gonystylus', species_epithet: 'bancanus',
    growth_form: 'tree', conservation: 'CR',
    description: 'A peat swamp timber tree, pale and even-grained, so heavily traded that it was listed on CITES Appendix II. Regeneration is poor wherever peat has been drained or burned.',
    characteristics: 'Slender bole to 30 m with stilt-like lower buttresses. Depends on intact waterlogged peat; drainage for plantations is the main threat.',
    leaf_description: 'Alternate, elliptic, 6-14 cm, glossy above with fine parallel veins and a drip tip.',
    flower_description: 'Small greenish-cream flowers in terminal panicles.',
    fruit_description: 'A three-lobed woody capsule 3-5 cm opening to expose seeds with an orange aril taken by hornbills.',
    habitat: 'Deep ombrogenous peat swamp forest, usually where peat exceeds one metre.',
    distribution: 'Borneo, Sumatra and Peninsular Malaysia. Sarawak peat swamps hold a significant share of what remains.',
  },
  {
    scientific_name: 'Agathis borneensis', common_name: 'Borneo kauri', local_name: 'Bindang',
    family: 'Araucariaceae', genus: 'Agathis', species_epithet: 'borneensis',
    growth_form: 'tree', conservation: 'EN',
    description: 'A conifer among tropical broadleaf giants, with a straight columnar trunk and flaking bark that bleeds copious white resin, once collected as the copal of commerce.',
    characteristics: 'One of very few native conifers in Borneo. Resin was traded for varnish and torches. Slow to regenerate after logging.',
    leaf_description: 'Opposite, leathery, elliptic to oblong, 5-12 cm, with no midrib and many fine parallel veins, unusual for a conifer.',
    flower_description: 'Not flowering. Male cones cylindrical 2-5 cm; female cones globose on short stout stalks.',
    fruit_description: 'A near-spherical cone 6-10 cm that disintegrates on the tree, releasing winged seeds.',
    habitat: 'Kerangas and peat swamp margins on poor acidic sandy soils, and on ridge crests.',
    distribution: 'Borneo, Sumatra, Peninsular Malaysia and the Philippines.',
  },
  {
    scientific_name: 'Licuala orbicularis', common_name: 'Round-leaf fan palm', local_name: 'Palas Bulat',
    family: 'Arecaceae', genus: 'Licuala', species_epithet: 'orbicularis',
    growth_form: 'palm', conservation: 'VU',
    description: 'A stemless understorey palm whose leaf is a single pleated disc up to a metre across, undivided and almost perfectly circular, one of the most distinctive plants in Sarawak.',
    characteristics: 'Endemic to Sarawak and much sought after by collectors, which is the main pressure on wild populations. Grows very slowly in deep shade.',
    leaf_description: 'Orbicular, entire, pleated, 60-100 cm across, held on a slender spiny petiole 1-2 m long.',
    flower_description: 'Small cream flowers on a slender branched inflorescence shorter than the leaves.',
    fruit_description: 'Globose, 8-12 mm, ripening orange to red, taken by ground birds.',
    habitat: 'Deeply shaded understorey of lowland mixed dipterocarp forest on humid clay slopes and stream banks.',
    distribution: 'Endemic to western Sarawak, mainly the Kuching and Sri Aman divisions.',
  },
  {
    scientific_name: 'Artocarpus odoratissimus', common_name: 'Terap', local_name: 'Terap / Marang',
    family: 'Moraceae', genus: 'Artocarpus', species_epithet: 'odoratissimus',
    growth_form: 'tree', conservation: 'LC',
    description: 'A jackfruit relative bearing a strongly fragrant fruit with soft white segments, widely regarded as one of the finest fruits of Borneo.',
    characteristics: 'All parts exude white latex. Cultivated in village orchards throughout Sarawak and Sabah as well as growing wild.',
    leaf_description: 'Very large, to 50 cm, obovate, three-lobed on juvenile shoots, rough above and hairy below.',
    flower_description: 'Unisexual heads on the same tree; male heads club-shaped, female heads globose.',
    fruit_description: 'A syncarp 15-20 cm covered in soft green bristles, opening to reveal sweet white perianth segments around each seed.',
    habitat: 'Lowland forest and village orchards on well-drained soils below 1000 m.',
    distribution: 'Native to Borneo and Palawan; cultivated across island Southeast Asia.',
  },
  {
    scientific_name: 'Durio graveolens', common_name: 'Red-fleshed durian', local_name: 'Durian Isu',
    family: 'Malvaceae', genus: 'Durio', species_epithet: 'graveolens',
    growth_form: 'tree', conservation: 'LC',
    description: 'A wild durian with vivid orange to crimson flesh and a mild, nutty scent far gentler than the common durian. Increasingly planted as a specialty fruit.',
    characteristics: 'Bat-pollinated, with flowers opening at dusk. One of several wild Durio species in Borneo that are important genetic resources for the cultivated crop.',
    leaf_description: 'Alternate, oblong, 10-20 cm, dark green above with a dense coppery-scaly underside that flashes in the wind.',
    flower_description: 'Golden to reddish, borne on the trunk and larger branches, opening in the evening for nectar-feeding bats.',
    fruit_description: 'Ovoid, 12-18 cm, with short broad pyramidal spines, splitting on the tree to show orange or red arils.',
    habitat: 'Lowland and hill mixed dipterocarp forest to about 1000 m, often on sandy or loamy ridges.',
    distribution: 'Borneo, Sumatra and Peninsular Malaysia; widely grown in Sarawak smallholdings.',
  },
  {
    scientific_name: 'Etlingera elatior', common_name: 'Torch ginger', local_name: 'Bunga Kantan',
    family: 'Zingiberaceae', genus: 'Etlingera', species_epithet: 'elatior',
    growth_form: 'herb', conservation: 'NE',
    description: 'A robust clumping ginger to 6 m whose waxy pink inflorescence rises on its own leafless stalk directly from the rhizome. The flower bud is a staple of Southeast Asian cooking.',
    characteristics: 'Forms large colonies from creeping rhizomes. Buds are used in laksa and sambal; the plant is equally common as an ornamental hedge.',
    leaf_description: 'Lanceolate, to 80 cm, arranged in two ranks along tall reed-like pseudostems.',
    flower_description: 'A torch-like head 10-15 cm of glossy pink to red bracts on a stalk 1-1.5 m tall, arising separately from the leafy shoots.',
    fruit_description: 'A crowded head of reddish hairy capsules holding small black seeds in white pulp.',
    habitat: 'Damp forest edges, stream banks, cultivated ground and village plots in full to partial sun.',
    distribution: 'Native to Southeast Asia and naturalised widely; common throughout Sarawak.',
  },
  {
    scientific_name: 'Dillenia suffruticosa', common_name: 'Shrubby simpoh', local_name: 'Simpoh Air',
    family: 'Dilleniaceae', genus: 'Dillenia', species_epithet: 'suffruticosa',
    growth_form: 'shrub', conservation: 'LC',
    description: 'A fast-growing pioneer shrub of roadsides and wet open ground, with large yellow flowers that last a single morning and star-shaped fruits that split at dawn.',
    characteristics: 'The big leaves are traditionally used to wrap tempeh and market food. Colonises disturbed and waterlogged land quickly, which makes it useful for restoration screening.',
    leaf_description: 'Broadly obovate, 15-30 cm, thick, with a strongly corrugated surface and prominent parallel side veins.',
    flower_description: 'Bright yellow, 8-12 cm across, with five crumpled petals and a dense boss of stamens; open for one morning only.',
    fruit_description: 'A star-shaped follicle opening at first light into pink-red segments with blue-black seeds in scarlet arils, taken immediately by birds.',
    habitat: 'Wet secondary scrub, roadside ditches, swamp margins and abandoned land in full sun.',
    distribution: 'Borneo, Sumatra, Peninsular Malaysia and Singapore; abundant across lowland Sarawak.',
  },
  {
    scientific_name: 'Calamus caesius', common_name: 'Sega rattan', local_name: 'Rotan Sega',
    family: 'Arecaceae', genus: 'Calamus', species_epithet: 'caesius',
    growth_form: 'climber', conservation: 'NT',
    description: 'The most valuable small-diameter rattan in the region, producing a pale, even, flexible cane that is the standard raw material for quality furniture binding.',
    characteristics: 'Clustering, climbing to 40 m by whip-like flagella armed with recurved hooks. Heavily harvested from the wild; now also planted under forest canopy.',
    leaf_description: 'Pinnate to 1.5 m, with regularly arranged narrow leaflets and a spiny sheath bearing a long grapnel-tipped cirrus.',
    flower_description: 'Dioecious, on slender branched inflorescences emerging from the leaf sheaths.',
    fruit_description: 'Rounded, about 1 cm, covered in neat overlapping whitish scales, with a single seed.',
    habitat: 'Lowland dipterocarp and freshwater swamp forest, often on alluvial soils near rivers.',
    distribution: 'Borneo, Sumatra, Peninsular Malaysia and Palawan.',
  },
  {
    scientific_name: 'Alocasia longiloba', common_name: 'Tiger taro', local_name: 'Keladi Hutan',
    family: 'Araceae', genus: 'Alocasia', species_epithet: 'longiloba',
    growth_form: 'herb', conservation: 'LC',
    description: 'A shade-loving aroid with arrow-shaped leaves marked by bold silver-white veins against dark green, held stiffly upright on spotted petioles.',
    characteristics: 'Highly variable across its range with many named forms. Sap contains calcium oxalate crystals and irritates skin.',
    leaf_description: 'Arrow-shaped, 20-50 cm, dark green with silvery primary veins and a paler purplish underside.',
    flower_description: 'A pale green spathe enclosing a cream spadix, pollinated by drosophilid flies.',
    fruit_description: 'A cluster of orange-red berries exposed as the spathe withers.',
    habitat: 'Damp shaded understorey, stream banks and limestone bases in lowland and hill forest.',
    distribution: 'Borneo, Sumatra, Peninsular Malaysia, Java and Thailand.',
  },
  {
    scientific_name: 'Begonia chlorosticta', common_name: 'Spotted begonia', local_name: null,
    family: 'Begoniaceae', genus: 'Begonia', species_epithet: 'chlorosticta',
    growth_form: 'herb', conservation: 'EN',
    description: 'A small Sarawak endemic begonia with asymmetric leaves patterned in bright green or silver spots over a near-black or deep red ground, known from very few localities.',
    characteristics: 'Restricted to shaded sandstone and limestone outcrops. Highly prized in cultivation, and wild collecting is a genuine threat to the small known populations.',
    leaf_description: 'Obliquely ovate, 6-12 cm, dark olive to blackish-red with scattered pale green spots and a red underside.',
    flower_description: 'White to pale pink, monoecious, in small cymes held just above the foliage.',
    fruit_description: 'A three-winged capsule with one wing longer than the others, releasing dust-fine seeds.',
    habitat: 'Deep shade on damp rock faces, cliff bases and stream gullies in lowland forest.',
    distribution: 'Endemic to Sarawak, known from a handful of sites in the Bau and Serian areas.',
  },
  {
    scientific_name: 'Vatica venulosa', common_name: 'Resak', local_name: 'Resak Daun Halus',
    family: 'Dipterocarpaceae', genus: 'Vatica', species_epithet: 'venulosa',
    growth_form: 'tree', conservation: 'EN',
    description: 'A medium-sized dipterocarp of riverbanks and lower slopes, yielding a hard heavy timber traded as resak and a clear dammar resin.',
    characteristics: 'Bark smooth to slightly scaly, grey-brown, exuding pale resin when cut. Populations fragmented by lowland clearance.',
    leaf_description: 'Elliptic to oblong, 8-18 cm, with distinctly raised fine net venation on the underside.',
    flower_description: 'Small, white to pale pink, fragrant, in short axillary panicles.',
    fruit_description: 'A nut 1-2 cm with two enlarged wings and three short lobes at the base.',
    habitat: 'Riverine and lower slope mixed dipterocarp forest on alluvium and clay, below 600 m.',
    distribution: 'Borneo, Sumatra and Peninsular Malaysia.',
  },
  {
    scientific_name: 'Macaranga gigantea', common_name: 'Giant macaranga', local_name: 'Mahang Gajah',
    family: 'Euphorbiaceae', genus: 'Macaranga', species_epithet: 'gigantea',
    growth_form: 'tree', conservation: 'LC',
    description: 'A very fast pioneer with huge shield-shaped leaves that dominates forest gaps, logging roads and abandoned farmland within a few years of disturbance.',
    characteristics: 'Hollow twigs of related species house Crematogaster ants in a classic ant-plant partnership. Short-lived, and normally displaced as primary forest species return.',
    leaf_description: 'Shield-shaped, broadly ovate, 30-60 cm across, shallowly three-lobed, whitish and hairy beneath.',
    flower_description: 'Dioecious; small yellowish flowers in large much-branched panicles.',
    fruit_description: 'A small two-lobed capsule covered in yellow resinous glands, with black seeds taken by bulbuls.',
    habitat: 'Forest gaps, landslips, logging roads, riverbanks and secondary growth in full sun.',
    distribution: 'Borneo, Sumatra, Peninsular Malaysia and Thailand; abundant in disturbed Sarawak lowlands.',
  },
  {
    scientific_name: 'Nephelium ramboutan-ake', common_name: 'Pulasan', local_name: 'Pulasan',
    family: 'Sapindaceae', genus: 'Nephelium', species_epithet: 'ramboutan-ake',
    growth_form: 'tree', conservation: 'LC',
    description: 'A close relative of rambutan with a thicker dark red rind and short blunt tubercles rather than soft spines, and a sweeter flesh that separates cleanly from the seed.',
    characteristics: 'Grown in village orchards across Borneo and traded in local markets. Fruiting is seasonal and often follows a dry spell.',
    leaf_description: 'Pinnate with 2-5 pairs of elliptic leaflets, each 7-18 cm, glossy above and dull below.',
    flower_description: 'Small greenish-white flowers in terminal panicles, faintly scented.',
    fruit_description: 'Ellipsoid, 5-8 cm, dark red with thick blunt tubercles, the white aril sweet and free from the seed.',
    habitat: 'Lowland forest and cultivated orchards on well-drained soils below 500 m.',
    distribution: 'Native to Borneo, Sumatra and Peninsular Malaysia; widely cultivated.',
  },
];
